name: capturador_datos_offline
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path: ^1.8.3

  amplify_flutter: ^2.0.0
  amplify_api: ^2.0.0
  amplify_datastore: ^2.0.0
  amplify_secure_storage: ^0.5.16
  amplify_auth_cognito: ^2.0.0

  just_audio: ^0.9.39
  audio_session: ^0.1.21
  record: ^6.2.0
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5
  share_plus: ^12.0.2
  pdf: ^3.12.0
  printing: ^5.14.3
  signature: ^5.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: Typographica
      fonts:
        - asset: "assets/Fonts/TypoGraphica.otf"
    - family: ChampagneLimousinesBold
      fonts:
        - asset: "assets/Fonts/Champagne & Limousines.ttf"
    - family: FuturaBold
      fonts:
        - asset: "assets/Fonts/Futura Bold.otf"

  uses-material-design: true